package com.example.skb_android.vacancy.model

import java.time.OffsetDateTime
import java.time.format.DateTimeFormatter

val dateFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ssZ")

val listShortVacanciesInfo = listOf<ShortVacancyModel>(
    ShortVacancyModel(
        id = "130480637",
        vacancyUrl = "https://hh.ru/vacancy/130480637",
        name = "Сборщик / Комплектовщик заказов",
        salaryFrom = 114900,
        salaryTo = 150100,
        salaryModeName = "За месяц",
        publishedAt = OffsetDateTime.parse("2026-02-16T12:10:49+0300", dateFormatter),
        employerName = "Сервис+ служба доставки",
        employerUrl = "https://hh.ru/employer/8639172",
        employerLogoUrl = "https://img.hhcdn.ru/employer-logo-round/6600306.png",
        areaName = "Реутов (Московская область)"
    ),
    ShortVacancyModel(
        id = "131160653",
        vacancyUrl = "https://hh.ru/vacancy/131160653",
        name = "Наборщик текста",
        salaryFrom = null,
        salaryTo = null,
        salaryModeName = null,
        publishedAt = OffsetDateTime.parse("2026-03-12T11:10:32+0300", dateFormatter),
        employerName = "Могилевский ф-л РУП БелЮрОбеспечение",
        employerUrl = "https://hh.ru/employer/3275020",
        employerLogoUrl = null,
        areaName = "Могилев"
    ),
    ShortVacancyModel(
        id = "131116144",
        vacancyUrl = "https://hh.ru/vacancy/131116144",
        name = "Водители автобетономешалки и самосвала",
        salaryFrom = 450000,
        salaryTo = 700000,
        salaryModeName = "За месяц",
        publishedAt = OffsetDateTime.parse("2026-03-11T10:50:31+0300", dateFormatter),
        employerName = "Салтанат",
        employerUrl = "https://hh.ru/employer/5285307",
        employerLogoUrl = null,
        areaName = "Алматы"
    ),
    ShortVacancyModel(
        id = "131222136",
        vacancyUrl = "https://hh.ru/vacancy/131222136",
        name = "Водитель",
        salaryFrom = 4000000,
        salaryTo = 7000000,
        salaryModeName = "За месяц",
        publishedAt = OffsetDateTime.parse("2026-03-14T13:53:09+0300", dateFormatter),
        employerName = "Yasin Collection",
        employerUrl = "https://hh.ru/employer/3109961",
        employerLogoUrl = "https://img.hhcdn.ru/employer-logo-round/2335401.png",
        areaName = "Ташкент"
    ),
    ShortVacancyModel(
        id = "121967902",
        vacancyUrl = "https://hh.ru/vacancy/121967902",
        name = "Водитель частной компании категории B",
        salaryFrom = 1215,
        salaryTo = null,
        salaryModeName = "За месяц",
        publishedAt = OffsetDateTime.parse("2026-03-02T12:25:02+0300", dateFormatter),
        employerName = "Журавлев Александр Сергеевич",
        employerUrl = "https://hh.ru/employer/5756414",
        employerLogoUrl = null,
        areaName = "Минск"
    ),
    ShortVacancyModel(
        id = "131096538",
        vacancyUrl = "https://hh.ru/vacancy/131096538",
        name = "Оператор чата интернет магазина (без звонков)",
        salaryFrom = 40000,
        salaryTo = 60000,
        salaryModeName = "За месяц",
        publishedAt = OffsetDateTime.parse("2026-03-10T16:48:37+0300", dateFormatter),
        employerName = "DOGBON",
        employerUrl = "https://hh.ru/employer/12645504",
        employerLogoUrl = "https://img.hhcdn.ru/employer-logo/12267412.png",
        areaName = "Москва"
    ),
    ShortVacancyModel(
        id = "131020274",
        vacancyUrl = "https://hh.ru/vacancy/131020274",
        name = "Официант",
        salaryFrom = 200000,
        salaryTo = 400000,
        salaryModeName = "За смену",
        publishedAt = OffsetDateTime.parse("2026-03-06T09:37:18+0300", dateFormatter),
        employerName = "HELEN (makkoli.uz)",
        employerUrl = "https://hh.ru/employer/10765950",
        employerLogoUrl = null,
        areaName = "Ташкент"
    ),
    ShortVacancyModel(
        id = "131209464",
        vacancyUrl = "https://hh.ru/vacancy/131209464",
        name = "Водитель автомобиля",
        salaryFrom = 234234,
        salaryTo = 234234,
        salaryModeName = "За месяц",
        publishedAt = OffsetDateTime.parse("2026-03-13T15:08:43+0300", dateFormatter),
        employerName = "Уральская Газотурбинная Электростанция",
        employerUrl = "https://hh.ru/employer/3167507",
        employerLogoUrl = null,
        areaName = "Уральск"
    ),
    ShortVacancyModel(
        id = "131159625",
        vacancyUrl = "https://hh.ru/vacancy/131159625",
        name = "Работник в офисе",
        salaryFrom = 1000,
        salaryTo = 1500,
        salaryModeName = "За месяц",
        publishedAt = OffsetDateTime.parse("2026-03-12T10:58:11+0300", dateFormatter),
        employerName = "Ледники Кавказа",
        employerUrl = "https://hh.ru/employer/12368165",
        employerLogoUrl = null,
        areaName = "Гродно"
    ),
    ShortVacancyModel(
        id = "131205224",
        vacancyUrl = "https://hh.ru/vacancy/131205224",
        name = "Бухгалтер",
        salaryFrom = 1000000,
        salaryTo = null,
        salaryModeName = "За месяц",
        publishedAt = OffsetDateTime.parse("2026-03-13T13:45:50+0300", dateFormatter),
        employerName = "KURE GRUP",
        employerUrl = "https://hh.ru/employer/9464746",
        employerLogoUrl = null,
        areaName = "Алматы"
    ),
)

val listFullVacanciesInfo = listOf<FullVacancyModel>(
    FullVacancyModel(
        id = "130480637",
        vacancyUrl = "https://hh.ru/vacancy/130480637",
        name = "Сборщик / Комплектовщик заказов",
        salaryFrom = 114900,
        salaryTo = 150100,
        salaryModeName = "За месяц",
        publishedAt = OffsetDateTime.parse("2026-02-16T12:10:49+0300", dateFormatter),
        employerName = "Сервис+ служба доставки",
        employerUrl = "https://hh.ru/employer/8639172",
        employerLogoUrl = "https://img.hhcdn.ru/employer-logo-round/6600306.png",
        areaName = "Реутов (Московская область)",
        experienceName = "Нет опыта",
        description = """
            <p>Подарим 500руб за отклик и регистрацию на нашем сайте</p> <p>Ищем на подработку или постоянную работу в тёплом помещении: Сборщик / Комплектовщик заказов. Опыт не важен, график свободный</p> <p><strong>Оставь отклик и получи предложение! Это тебя ни к чему не обязывает.</strong></p> <ul> <li>Ты ознакомишься с перечнем смен и примешь решение</li> <li>Чтобы выйти на смену, проходить собеседования не нужно</li> <li>Отвлекать звонками тебя не будем.</li> </ul> <p><strong>- без собеседований<br />- с ежедневными выплатами<br />- без оформления самозанятости или с ней<br />- рядом с домом или в любом районе города</strong></p> <p><strong>Бонусы, если сделаете свой отклик сейчас:</strong><br />- <strong>5500 р</strong> в виде скидки на продукты, сервисы, товары после выполнения 10й смены<br />- Работа без мед.книжки или <strong>компенсация до 3000 р</strong> на её оформление/продление</p> <p> </p> <p><strong>Обязанности:</strong></p> <ul> <li>Работа в теплом складе супермаркетов федерального уровня, которые знают все.</li> <li>Сборка, комплектовка заказов</li> </ul> <p> </p> <strong>Требования:</strong> <ul> <li>Желание найти постоянную работу или подработку рядом с домом со свободным графиком</li> </ul> <p> </p> <strong>Условия:</strong> <ul> <li>Гарантия ежедневной выплаты зарплаты</li> <li>Выбор смены на своё усмотрение</li> </ul> <p> </p> <p>Пригодится опыт работы, но можно и без опыта работы: грузчик, разнорабочий</p> <p> </p> <p>Делайте отклик. Осталось 9 мест, пока объявление на сайте - оно актуально</p> <p> </p> <p>Чтобы получить все бонусы, необходимо связаться с менеджером и зарегистрировать на нашем сайте на интересуемую вакансию</p>
        """.trimIndent(),
        skills = listOf() // из key_skills
    ),
    FullVacancyModel(
        id = "131160653",
        vacancyUrl = "https://hh.ru/vacancy/131160653",
        name = "Наборщик текста",
        salaryFrom = null,
        salaryTo = null,
        salaryModeName = null,
        publishedAt = OffsetDateTime.parse("2026-03-12T11:10:32+0300", dateFormatter),
        employerName = "Могилевский ф-л РУП БелЮрОбеспечение",
        employerUrl = "https://hh.ru/employer/3275020",
        employerLogoUrl = null,
        areaName = "Могилев",
        experienceName = "От 1 года до 3 лет",
        description = """<strong>Обязанности:</strong> <ul> <li>набор текста </li> <li> </li> </ul> <strong>Требования:</strong> <ul> <li>опыт работы с ПК;</li> <li>навыки работы с базовыми программами;</li> <li>грамотность;</li> <li>хорошая скорость печати;</li> </ul> <strong>Условия:</strong> <ul> <li>оформление по ТК РБ;</li> <li> </li> </ul> <strong>Ссылка на вакансию в банке вакансий на gsz.gov.⁣by:</strong> <div> </div>""",
        skills = listOf()
    ),
    FullVacancyModel(
        id = "131116144",
        vacancyUrl = "https://hh.ru/vacancy/131116144",
        name = "Водители автобетономешалки и самосвала",
        salaryFrom = 450000,
        salaryTo = 700000,
        salaryModeName = "За месяц",
        publishedAt = OffsetDateTime.parse("2026-03-11T10:50:31+0300", dateFormatter),
        employerName = "Салтанат",
        employerUrl = "https://hh.ru/employer/5285307",
        employerLogoUrl = null,
        areaName = "Алматы",
        experienceName = "От 1 года до 3 лет",
        description = """<strong>Обязанности:</strong> <ul> <li>Обеспечение целостной и своевременной перевозки требуемых грузов</li> <li>Поддержание чистоты и исправности грузовика</li> </ul> <strong>Требования:</strong> <ul> <li>Соблюдение ПДД</li> <li>Бережное отношение к автомобилю</li> </ul> <strong>Условия:</strong> <ul> <li>Ответственность и дисциплина</li> </ul>""",
        skills = listOf("Автомобильные перевозки")
    ),
    FullVacancyModel(
        id = "131222136",
        vacancyUrl = "https://hh.ru/vacancy/131222136",
        name = "Водитель",
        salaryFrom = 4000000,
        salaryTo = 7000000,
        salaryModeName = "За месяц",
        publishedAt = OffsetDateTime.parse("2026-03-14T13:53:09+0300", dateFormatter),
        employerName = "Yasin Collection",
        employerUrl = "https://hh.ru/employer/3109961",
        employerLogoUrl = "https://img.hhcdn.ru/employer-logo-round/2335401.png",
        areaName = "Ташкент",
        experienceName = "От 1 года до 3 лет",
        description = """<strong>Обязанности:</strong> <ul> <li><strong>Управление транспортным средством</strong> – безопасное и аккуратное вождение, соблюдение ПДД.</li> <li><strong>Контроль технического состояния</strong> – проверка автомобиля перед выездом (масло, тормоза, шины и т. д.).</li> <li><strong>Заправка и уход за автомобилем</strong> – заправка топливом, мойка и поддержание чистоты.</li> <li><strong>Оформление путевых документов</strong> – ведение отчетности по маршрутам, пробегу и расходу топлива.</li> <li><strong>Соблюдение графика</strong> – своевременная подача автомобиля и выполнение маршрута.</li> <li><strong>Коммуникация с диспетчером</strong> – оперативное информирование о задержках или проблемах.</li> <li><strong>Соблюдение правил безопасности</strong> – вождение без нарушений, работа с грузом (если требуется).</li> <li>Выполнять поручения руководителя!</li> </ul> <p><strong>Требования:</strong></p> <p><strong>Знание русского и узбекского языка</strong></p> <ul> <li><strong>Опыт вождения</strong> – от 1 года и выше (в зависимости от вакансии).</li> <li><strong>Хорошее знание ПДД</strong> – понимание правил дорожного движения и знание местности.</li> <li><strong>Ответственность и дисциплинированность</strong> – внимательное отношение к работе.</li> <li><strong>Физическая выносливость</strong> – если работа связана с тяжелыми грузами.</li> <li><strong>Навыки ремонта</strong> – базовые знания технического обслуживания автомобиля.</li> <li><strong>Хорошая реакция и стрессоустойчивость</strong> – умение быстро реагировать в экстренных ситуациях.</li> </ul> <p><strong>Условия:</strong></p> <p><strong>Служебный автомобиль</strong> – предоставляется компанией, могут быть требования к аккуратности и техобслуживанию.</p> <p><strong>Дружный коллектив </strong></p> <p><strong>График работы : 9-19:00, 6/1</strong></p> <p><strong>Обед от компании. </strong></p> <p> </p>""",
        skills = listOf()
    ),
    FullVacancyModel(
        id = "121967902",
        vacancyUrl = "https://hh.ru/vacancy/121967902",
        name = "Водитель частной компании категории B",
        salaryFrom = 1215,
        salaryTo = null,
        salaryModeName = "За месяц",
        publishedAt = OffsetDateTime.parse("2026-03-02T12:25:02+0300", dateFormatter),
        employerName = "Журавлев Александр Сергеевич",
        employerUrl = "https://hh.ru/employer/5756414",
        employerLogoUrl = null,
        areaName = "Минск",
        experienceName = "Нет опыта",
        description = """<p><em>Срочная вакансия водителя в компанию. Подработка со свободным графиком и ежедневной оплатой! Опыт не нужен. Возможность работы на любом автомобиле и в любом районе города.</em></p> <p>Работа на территории Минска, оформление по ТК РБ.</p> <p><strong>Обязанности:</strong></p> <ul> <li>Доставка оплаченных заказов до клиентов</li> </ul> <p><strong>Требования:</strong></p> <ul> <li>Права категории B</li> </ul> <p><strong>Условия:</strong></p> <ul> <li>Ежедневная оплата плюс чаевые</li> <li>Доход до 300 бел. руб. в час</li> <li>Работа в комфортном для Вас ритме и графике</li> <li>Отсутствие штрафов, планов и прочих &quot;радостей&quot;</li> <li>Подработка от 2х часов в день в удобном районе</li> <li>Мгновенный старт</li> </ul> <p>Будет преимуществом опыт работы на таких позиция как: водитель, водитель-курьер, водитель категории B, водитель служебного автомобиля, водитель на своём автомобиле, водитель экспедитор, доставщик, автокурьер, водитель выходного дня, подработка водителем от 4х часов, подработка автокурьером на выходных, подработка с ежедневной оплатой.</p> <p>Жмите &quot;<strong>Откликнуться</strong>&quot; прямо сейчас и начинайте зарабатывать.</p> <p>ОБРАЩАЕМ ВНИМАНИЕ, после отклика на данную вакансию потребуется предоставление информации или выполнение иных действий на сторонних информационных ресурсах.</p> <p> </p>""",
        skills = listOf("Курьерская доставка")
    ),
    FullVacancyModel(
        id = "131096538",
        vacancyUrl = "https://hh.ru/vacancy/131096538",
        name = "Оператор чата интернет магазина (без звонков)",
        salaryFrom = 40000,
        salaryTo = 60000,
        salaryModeName = "За месяц",
        publishedAt = OffsetDateTime.parse("2026-03-10T16:48:37+0300", dateFormatter),
        employerName = "DOGBON",
        employerUrl = "https://hh.ru/employer/12645504",
        employerLogoUrl = "https://img.hhcdn.ru/employer-logo/12267412.png",
        areaName = "Москва",
        experienceName = "Нет опыта",
        description = """<p><strong>Задачи:</strong></p> <ul> <li> <p>Отвечать на сообщения клиентов на сайте и в мессенджерах.</p> </li> <li> <p>Отправлять ссылки на товары и инструкции.</p> </li> <li> <p>Передавать сложные вопросы менеджеру.</p> </li> </ul> <p><strong>Требования к кандидату:</strong></p> <ul> <li> <p>Вежливость и доброжелательность.</p> </li> <li> <p>Умение быстро ориентироваться в информации.</p> </li> <li> <p>Можно без опыта, всему обучим.</p> </li> </ul> <p><strong>Мы предлагаем</strong></p> <ul> <li> <p>Доход: <strong>40 000 – 60 000 руб.</strong> (фикс + бонусы).</p> </li> <li> <p>График: <strong>4 часа в день</strong>, возможна подработка.</p> </li> <li> <p>Полностью <strong>удаленная работа</strong>.</p> </li> <li> <p>Бесплатное обучение и готовые шаблоны ответов.</p> </li> <li> <p>Поддержка наставника на старте.</p> </li> </ul>""",
        skills = listOf(
            "Деловое общение",
            "Деловая переписка",
            "Пользователь ПК",
            "Коммуникабельность",
            "Ориентация на клиента",
            "Ведение переписки"
        )
    ),
    FullVacancyModel(
        id = "131020274",
        vacancyUrl = "https://hh.ru/vacancy/131020274",
        name = "Официант",
        salaryFrom = 200000,
        salaryTo = 400000,
        salaryModeName = "За смену",
        publishedAt = OffsetDateTime.parse("2026-03-06T09:37:18+0300", dateFormatter),
        employerName = "HELEN (makkoli.uz)",
        employerUrl = "https://hh.ru/employer/10765950",
        employerLogoUrl = null,
        areaName = "Ташкент",
        experienceName = "От 1 года до 3 лет",
        description = """<p>Требования:</p> <p> </p> <ul> <li>Опыт работы официантом приветствуется (но не обязателен)</li> <li>Аккуратный внешний вид</li> <li>Вежливость, ответственность, пунктуальность</li> <li>Умение работать в команде</li> <li>Знание меню или готовность быстро его выучить</li> </ul> <p> </p> <p> </p> <p>Условия:</p> <p> </p> <ul> <li>Сменный график работы</li> <li>Своевременная выплата заработной платы</li> <li>Бесплатное питание</li> <li>Обучение и стажировка</li> <li>Дружный коллектив</li> </ul> <p> </p>""",
        skills = listOf()
    ),
    FullVacancyModel(
        id = "131209464",
        vacancyUrl = "https://hh.ru/vacancy/131209464",
        name = "Водитель автомобиля",
        salaryFrom = 234234,
        salaryTo = 234234,
        salaryModeName = "За месяц",
        publishedAt = OffsetDateTime.parse("2026-03-13T15:08:43+0300", dateFormatter),
        employerName = "Уральская Газотурбинная Электростанция",
        employerUrl = "https://hh.ru/employer/3167507",
        employerLogoUrl = null,
        areaName = "Уральск",
        experienceName = "От 3 до 6 лет",
        description = """<strong>Обязанности:</strong> <p>Осуществлять:</p> <ul> <li>заправку автомобиля топливом, смазочными материалами и охлаждающей жидкостью;</li> <li>оформление путевых документов;</li> <li>проверку технического состояния и прием автомобиля перед выездом на линию;</li> <li>постановку его на отведенное место по возвращению с работы;</li> <li>подачу автомобиля под погрузку грузов, а также под разгрузку грузов;</li> <li>осуществлять контроль за правильностью погрузки;</li> <li>устранение возникших во время работы на линии мелких эксплуатационных неисправностей подвижного состава, не требующих разборки механизмов.</li> </ul> <p><strong>Требования</strong></p> <p>На должность водителя автомобиля 4 разряда назначается лицо, прошедшее медицинское освидетельствование, имеющее среднее образование, водительское удостоверение категории «В», «С», «D», «E» и опыт работы не менее 3 лет.<br /><strong>Условия труда нормальные</strong>​​​​​​​</p>""",
        skills = listOf()
    ),
    FullVacancyModel(
        id = "131159625",
        vacancyUrl = "https://hh.ru/vacancy/131159625",
        name = "Работник в офисе",
        salaryFrom = 1000,
        salaryTo = 1500,
        salaryModeName = "За месяц",
        publishedAt = OffsetDateTime.parse("2026-03-12T10:58:11+0300", dateFormatter),
        employerName = "Ледники Кавказа",
        employerUrl = "https://hh.ru/employer/12368165",
        employerLogoUrl = null,
        areaName = "Гродно",
        experienceName = "От 1 года до 3 лет",
        description = """Начните свой путь в офисной работе, где каждый день приносит новые задачи и возможности для развития!<br /><br /><strong>Обязанности</strong><br /><ul><li>Выписка товарно-транспортных накладных (ТТН)</li><li>Работа с программой 1С</li><li>Холодные звонки клиентам</li><li>Заключение договоров с клиентами</li></ul><strong>Требования</strong><br /><ul><li>Опыт работы с 1С и документооборотом</li><li>Коммуникабельность и умение вести переговоры</li><li>Ответственность и внимательность к деталям</li><li>Желание развиваться в офисной работе</li></ul><strong>Условия</strong><br /><ul><li>Стабильный график работы 5/2</li><li>Работа в офисе</li><li>Возможность профессионального роста</li></ul>""",
        skills = listOf()
    ),
    FullVacancyModel(
        id = "131205224",
        vacancyUrl = "https://hh.ru/vacancy/131205224",
        name = "Бухгалтер",
        salaryFrom = 1000000,
        salaryTo = null,
        salaryModeName = "За месяц",
        publishedAt = OffsetDateTime.parse("2026-03-13T13:45:50+0300", dateFormatter),
        employerName = "KURE GRUP",
        employerUrl = "https://hh.ru/employer/9464746",
        employerLogoUrl = null,
        areaName = "Алматы",
        experienceName = "От 3 до 6 лет",
        description = """<strong>Обязанности:</strong> <ul> <li>Знание всех участков бухгалтерии и налогового законодательства (Строительное производство, налоги, начисление з/п, Банк-Клиент, ТМЦ, Покупка, Реализация, ЭСФ, акты сверок, госзакуп)</li> <li>Сдача отчетности в Стат, НК, НБ, выполнять задания руководства</li> </ul> <strong>Требования:</strong> <ul> <li>Опыт работы от 3-х лет</li> </ul> <strong>Условия:</strong> <ul> <li>Официальное трудоустройство</li> <li>Соц.пакет</li> <li>График работы 5/2</li> </ul>""",
        skills = listOf(
            "Бухгалтерский баланс",
            "Бухгалтерский аудит",
            "Налоговые декларации",
            "Бумажный документооборот",
            "Планирование бюджета"
        )
    ),
)
